name: sae-database-writer

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: database_writer
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: