name: Build and Publish

on:
    push:

env:
    version: 0.5.0

jobs:
    build:
        name: "Building project with Java 21"
        runs-on: [self-hosted, linux, X64]

        steps:

            - name: setup internal maven registry
              uses: s4u/maven-settings-action@v2.8.0
              with:
                servers: |
                  [{
                      "id": "github2",
                      "username": "${{ vars.PRIVATE_REPO_USERNAME }}",
                      "password": "${{ secrets.MAVEN_REPO_READ }}"
                  }]
            - name: debug
              run: find .
            - name: debug2
              run: cat ~/.m2/settings.xml
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: 21
            - name: Set up Maven
              uses: stCarolas/setup-maven@v4.5
              with:
                maven-version: 3.9.6
            - name: Build with Maven           
              run: mvn clean package --file pom.xml
              env:
                CI: false

            - name: Upload Maven build artifact
              uses: actions/upload-artifact@v1
              with:
                name: artifact
                path: target/vision-api-consumer-$version.jar

            - name: Log in to the Container registry
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                registry: ${{ vars.INTERNAL_REGISTRY_URL }}
                username: docker
                password: ${{ secrets.INTERNAL_REGISTRY_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
              with:
                context: .
                push: true
                tags: ${{ vars.INTERNAL_REGISTRY_URL }}/sae/vision-api-jms-client:$version
                labels: "latest"