name: Build prerelease image

on:
  workflow_dispatch:

permissions:
  packages: read

env:
  IMAGE_NAME: sae-database-writer
  DOCKERHUB_USERNAME: starwit
  DOCKERHUB_ORG: starwitorg  

jobs:
  build:
    name: "Build and publish docker image"
    runs-on: [self-hosted, linux, X64]
    
    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
         maven-version: 3.9.2      

    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build with Maven
      run: mvn clean package -B --settings .github/workflows/settings.xml --file pom.xml
      env:
         CI: false
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get tag name
      run: |
        echo "TAG=$( git describe --abbrev=0 --tags )" >> $GITHUB_ENV
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        sbom: true
        provenance: mode=max
        tags: ${{ env.DOCKERHUB_ORG }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}-${{ github.run_number }}
