name: PR Build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  packages: read

jobs:
  build:
    name: "Build maven project"
    runs-on: [self-hosted, linux, X64]

    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
         maven-version: 3.9.11

    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Build with Maven
      run: mvn clean package -B --settings .github/workflows/settings.xml --file pom.xml
      env:
         CI: false
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


